'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {chromium}=require('playwright');
test('inspection reports original inline paint, bypasses selected subtree, and restores scanning',async t=>{const browser=await chromium.launch();t.after(()=>browser.close());const page=await browser.newPage();await page.setContent('<div id="target" style="height:150px;background:#fff;color:#fff"><span id="child">Unreadable fixture</span></div><div id="owned" data-exp-owned="1">Tool UI</div>');const source=fs.readFileSync(path.join(__dirname,'../vendor/exp-core/exp-core.js'),'utf8')+'\n'+['themes.js','color-engine.js','site-fixes.js','live-resolver.js','inspector.js'].map(f=>fs.readFileSync(path.join(__dirname,'../src',f),'utf8')).join('\n');await page.addScriptTag({content:`const EXP={};${source};window.exp=EXP;EXP.LiveResolver.start(EXP.Themes.resolve('midnight','site-default'));`});
await page.waitForFunction(()=>document.querySelector('#target').hasAttribute('data-exp-shift-live'));
const before=await page.evaluate(()=>exp.LiveResolver.inspectElement(document.querySelector('#target')));assert.ok(before.repairs.length);assert.ok(before.repairs.some(p=>p.property==='background-color'&&p.original));
await page.evaluate(()=>exp.Inspector.select(()=>{}));await page.locator('#owned').click();assert.equal(await page.locator('#owned').getAttribute('data-exp-shift-preserve'),null);await page.locator('#child').click();await page.evaluate(()=>exp.Inspector.preserve());assert.equal(await page.locator('#child').getAttribute('data-exp-shift-preserve'),'inspector');
await page.evaluate(()=>{exp.Inspector.resume();exp.Inspector.select(()=>{});});await page.locator('#target').click({position:{x:30,y:80}});await page.evaluate(()=>exp.Inspector.preserve());assert.equal(await page.locator('#target').evaluate(n=>n.style.backgroundColor),'rgb(255, 255, 255)');await page.evaluate(()=>exp.LiveResolver.scan());await page.waitForTimeout(200);assert.equal(await page.locator('#target').evaluate(n=>n.style.backgroundColor),'rgb(255, 255, 255)');await page.evaluate(()=>exp.Inspector.resume());await page.waitForFunction(()=>document.querySelector('#target').hasAttribute('data-exp-shift-live'));await page.evaluate(()=>{exp.Inspector.select(()=>{});exp.Inspector.destroy();exp.LiveResolver.stop();});assert.equal(await page.locator('[data-exp-shift-preserve="inspector"]').count(),0);});

test('saved element rules preserve replacement nodes and clear stale markers on settings changes',async t=>{const browser=await chromium.launch();t.after(()=>browser.close());const page=await browser.newPage();await page.setContent('<div id="target">Private page text</div>');const source=fs.readFileSync(path.join(__dirname,'../src/inspector.js'),'utf8');await page.addScriptTag({content:`const EXP={Settings:{snapshot:()=>window.state,replace:next=>{window.state=next;}},LiveResolver:{restoreElement(){},scan(){},inspectElement(){return {tag:'div',foreground:'',background:'',font:'',repairs:[]}}},Engine:{health:()=>({mode:'original'})}};window.state={siteOverrides:{}};${source};window.exp=EXP;document.body.append(EXP.Inspector.createControls());`});await page.getByText('Inspect readability',{exact:true}).click();await page.getByRole('button',{name:'Select page element',exact:true}).click();await page.locator('#target').click();await page.getByRole('button',{name:'Preserve selected element on this site',exact:true}).click();const state=await page.evaluate(()=>window.state);assert.equal(JSON.stringify(state).includes('Private page text'),false);assert.deepEqual(Object.values(state.siteOverrides)[0].preservedSelectors,['#target']);await page.evaluate(()=>{document.getElementById('target').outerHTML='<div id="target">Replacement</div>';exp.Inspector.applySaved();});assert.equal(await page.locator('#target').getAttribute('data-exp-shift-preserve'),'saved');await page.evaluate(()=>{window.state.siteOverrides={};exp.Inspector.applySaved();});assert.equal(await page.locator('#target').getAttribute('data-exp-shift-preserve'),null);});
